const PERSONAL_SOURCES_ACTION_INDEX = 0;
const ORG_SOURCES_ACTION_INDEX = 1;
const PUBLIC_SOURCES_ACTION_INDEX = 2;


export {
    PERSONAL_SOURCES_ACTION_INDEX,
    ORG_SOURCES_ACTION_INDEX,
    PUBLIC_SOURCES_ACTION_INDEX
};
