version: '2.1'
services:
  mongo:
    image: mongo:3.2.11
    restart: "no"
    healthcheck:
      test: "exit 0"
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  redis:
    image: redis:3.2.10
    restart: "no"
    healthcheck:
      test: "exit 0"
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  solr:
    image: openconceptlab/oclsolr:${ENVIRONMENT:-production}
    restart: "no"
    healthcheck:
      test: "exit 0"
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  api:
    build: .
    depends_on:
      - mongo
      - solr
      - redis
    links:
      - "mongo"
      - "redis"
      - "solr"
    ports:
      - "8000:8000"
    environment:
      - WAIT_FOR=mongo:27017,redis:6379,solr:8983
      - ROOT_PASSWORD=${ROOT_PASSWORD-Root123}
      - OCL_API_TOKEN=${OCL_API_TOKEN-891b4b17feab99f3ff7e5b5d04ccc5da7aa96da6}
      - IMPORT_DEMO_DATA=${IMPORT_DEMO_DATA-true}
      - SECRET_KEY
      - SENTRY_DSN_KEY
      - EMAIL_HOST_PASSWORD
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME
      - FLOWER_USER=${FLOWER_USER-floweruser}
      - FLOWER_PWD=${FLOWER_PWD-Flower123}
    restart: "no"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/authtoken/token/"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
