export default [
  {
    external_id: '2249AEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
    retired: false,
    map_type: 'CONCEPT-SET',
    source: 'CIEL',
    owner: 'CIEL',
    owner_type: 'Organization',
    from_concept_code: '657',
    from_concept_name: 'CD4 PANEL',
    from_concept_url: '/orgs/CIEL/sources/CIEL/concepts/657/',
    to_concept_url: '/orgs/CIEL/sources/CIEL/concepts/730/',
    to_source_url: '/orgs/CIEL/sources/CIEL/',
    to_concept_code: '730',
    to_concept_name: 'CD4%',
    url: '/orgs/CIEL/sources/CIEL/mappings/5cb5ae055ab3eb014346d8c2/',
    version: '1',
    id: '5cb5ae055ab3eb014346d8c3',
    versioned_object_id: '5cb5ae055ab3eb014346d8c2',
    from_source_owner: 'CIEL',
    from_source_owner_type: 'Organization',
    from_source_name: 'CIEL',
    from_source_url: '/orgs/CIEL/sources/CIEL/',
    to_source_owner: 'CIEL',
    to_source_owner_type: 'Organization',
    to_source_name: 'CIEL',
    versioned_object_url: '/orgs/CIEL/sources/CIEL/mappings/5cb5ae055ab3eb014346d8c2/',
    is_latest_version: true,
    update_comment: null,
    version_url: '/orgs/CIEL/sources/CIEL/mappings/5cb5ae055ab3eb014346d8c2/1/',
  },
  {
    external_id: '2276AEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
    retired: false,
    map_type: 'CONCEPT-SET',
    source: 'CIEL',
    owner: 'CIEL',
    owner_type: 'Organization',
    from_concept_code: '1361',
    from_concept_name: 'LABORATORY RESULTS',
    from_concept_url: '/orgs/CIEL/sources/CIEL/concepts/1361/',
    to_concept_url: '/orgs/CIEL/sources/CIEL/concepts/1042/',
    to_source_url: '/orgs/CIEL/sources/CIEL/',
    to_concept_code: '1042',
    to_concept_name: 'HIV ENZYME IMMUNOASSAY, QUALITATIVE',
    url: '/orgs/CIEL/sources/CIEL/mappings/5cb5ae175ab3eb014346dd02/',
    version: '1',
    id: '5cb5ae175ab3eb014346dd03',
    versioned_object_id: '5cb5ae175ab3eb014346dd02',
    from_source_owner: 'CIEL',
    from_source_owner_type: 'Organization',
    from_source_name: 'CIEL',
    from_source_url: '/orgs/CIEL/sources/CIEL/',
    to_source_owner: 'CIEL',
    to_source_owner_type: 'Organization',
    to_source_name: 'CIEL',
    versioned_object_url: '/orgs/CIEL/sources/CIEL/mappings/5cb5ae175ab3eb014346dd02/',
    is_latest_version: true,
    update_comment: null,
    version_url: '/orgs/CIEL/sources/CIEL/mappings/5cb5ae175ab3eb014346dd02/1/',
  }];

