export default {
  type: 'Organization',
  uuid: '8d94f280-c2cc-11de-8d13-0010c6dffd0f',
  id: 'My-Organization',
  name: 'My Organization',
  company: 'Company Name',
  website: 'http://myorganization.com/',
  location: 'Boston, MA, USA',
  public_access: 'View',
  extras: { 'extra-meta-data': 'my-value' },
  url: '/orgs/My-Organization/',
  members_url: '/orgs/My-Organization/members/',
  sources_url: '/orgs/My-Organization/sources/',
  collections_url: '/orgs/My-Organization/collections/',
  members: 2,
  public_collections: 1,
  public_sources: 1,
  created_on: '2008-01-14T04:33:35Z',
  created_by: 'johndoe',
  updated_on: '2008-02-18T09:10:16Z',
  updated_by: 'johndoe',
};
