export const internalSource = {
  type: 'Source',
  uuid: '5ce6bd64a70c96003fbd8b73',
  id: 'Locales',
  short_code: 'Locales',
  name: 'Locales',
  full_name: 'Locales',
  description: null,
  source_type: '',
  custom_validation_schema: null,
  public_access: 'View',
  default_locale: 'en',
  supported_locales: [
    'en',
  ],
  website: null,
  url: '/orgs/OCL/sources/Locales/',
  versions_url: '/orgs/OCL/sources/Locales/versions/',
  concepts_url: '/orgs/OCL/sources/Locales/concepts/',
  active_concepts: 485,
  active_mappings: 0,
  owner: 'OCL',
  owner_type: 'Organization',
  owner_url: '/orgs/OCL/',
  versions: 1,
  created_on: '2019-05-23T11:33:56.719',
  updated_on: '2019-05-23T11:33:56.719',
  created_by: 'root',
  updated_by: 'root',
  extras: null,
  external_id: null,
};

export const externalSource = {
  type: 'Source',
  uuid: '5c9dbf491671840155214dd9',
  id: 'SNOMED-CT',
  short_code: 'SNOMED-CT',
  name: 'SNOMED-CT',
  full_name: 'Systematized Nomenclature of Medicine--Clinical Terms',
  description: 'SNOMED-CT Preferred mapping',
  source_type: 'External',
  custom_validation_schema: null,
  public_access: 'View',
  default_locale: 'en',
  supported_locales: [
    'en',
  ],
  website: '',
  url: '/orgs/IHTSDO/sources/SNOMED-CT/',
  versions_url: '/orgs/IHTSDO/sources/SNOMED-CT/versions/',
  concepts_url: '/orgs/IHTSDO/sources/SNOMED-CT/concepts/',
  active_concepts: 0,
  active_mappings: 0,
  owner: 'IHTSDO',
  owner_type: 'Organization',
  owner_url: '/orgs/IHTSDO/',
  versions: 1,
  created_on: '2019-03-29T02:46:33.035',
  updated_on: '2019-03-29T02:46:33.035',
  created_by: 'root',
  updated_by: 'root',
  extras: {
    hl7_code: 'SCT',
  },
  external_id: '2b3c054a-768a-102f-83f4-12313b04a615',
};
