export default {
  type: 'User',
  uuid: '5b719ec5e5fc3e00c8ba5084',
  username: 'admin',
  name: 'Ian Duncan',
  email: 'admin@openconceptlab.org',
  company: null,
  location: null,
  preferred_locale: null,
  orgs: 0,
  public_collections: 0,
  public_sources: 0,
  created_on: '2018-08-13T11:07:49.657',
  updated_on: '2018-08-27T07:12:28.790',
  created_by: 'root',
  updated_by: 'testuser',
  url: '/users/testuser/',
  organizations_url: '/users/testuser/orgs/',
  sources_url: '/users/testuser/sources/',
  collections_url: '/users/testuser/collections/',
  extras: null,
};
